# Generated by Django 4.1.4 on 2023-03-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='no_of_rating',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='total_rating',
        ),
    ]
