# Generated by Django 4.1.4 on 2023-01-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_user_favourites_user_rate_listing_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rate_listing',
        ),
    ]
